### ISSUE TITLE
Failed to insert into network

### ISSUE THREAD

**Issue by capi92** [vk496/zigbee-herdsman-converters#16]
Hi,

Using latest edge version zigbee2mqtt. 
Default installation, no modification.

Version Zigbee2MQTT 1.23.0-dev commit: [b5e8566](https://github.com/Koenkk/zigbee2mqtt/commit/b5e8566)
Type de Coordinateur.    zStack3x0
Révision du Coordinateur.    20210120
Version Interface.  0.6.71

> warn  2022-02-05 23:11:18: Device '0x00158d0005be865e' left the network
warn  2022-02-05 23:11:24: Was not able to detect the Linky linky_mode. Default to historique
warn  2022-02-05 23:11:24: Was not able to detect the Linky energy_phase. Default to single_phase
error 2022-02-05 23:11:24: Failed to configure '0x00158d0005be865e', attempt 1 (Error: ConfigureReporting 0x00158d0005be865e/1 seMetering([{"attribute":"currentSummDelivered","minimumReportInterval":0,"maximumReportInterval":900,"reportableChange":100}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNREPORTABLE_ATTRIBUTE')
    at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:317:28)
    at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:649:22))
warn  2022-02-05 23:11:29: Was not able to detect the Linky linky_mode. Default to historique
warn  2022-02-05 23:11:29: Was not able to detect the Linky energy_phase. Default to single_phase
error 2022-02-05 23:11:30: Failed to configure '0x00158d0005be865e', attempt 2 (Error: ConfigureReporting 0x00158d0005be865e/1 seMetering([{"attribute":"currentSummDelivered","minimumReportInterval":0,"maximumReportInterval":900,"reportableChange":100}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNREPORTABLE_ATTRIBUTE')
    at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:317:28)
    at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:649:22))
warn  2022-02-05 23:11:36: Was not able to detect the Linky linky_mode. Default to historique
warn  2022-02-05 23:11:36: Was not able to detect the Linky energy_phase. Default to single_phase
error 2022-02-05 23:11:37: Failed to configure '0x00158d0005be865e', attempt 3 (Error: ConfigureReporting 0x00158d0005be865e/1 seMetering([{"attribute":"currentSummDelivered","minimumReportInterval":0,"maximumReportInterval":900,"reportableChange":100}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNREPORTABLE_ATTRIBUTE')
    at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:317:28)
    at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:649:22))
warn  2022-02-05 23:11:45: Device '0x00158d0005be865e' left the network
warn  2022-02-05 23:12:23: Device '0x00158d0005be865e' left the network
warn  2022-02-05 23:13:16: Device '0x00158d0005be865e' left the network

> (node:364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1114)

Was not able to detect the Linky linky_mode. Default to historique
Was not able to detect the Linky energy_phase. Default to single_phase
(node:364) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'manufacturerID' of undefined
    at /app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:115:81
    at Array.map (<anonymous>)
    at Endpoint.get configuredReportings [as configuredReportings] (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:114:43)
    at /app/node_modules/zigbee-herdsman-converters/devices/lixee.js:562:46
    at Array.filter (<anonymous>)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman-converters/devices/lixee.js:562:22)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)

**Comment by capi92** [comment]
Solved with 1.23.0-dev commit: [6394d0f](https://github.com/Koenkk/zigbee2mqtt/commit/6394d0f)
